version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging into amazon ECR
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region us-east-1
      - REPOSITORY_URI=161452358598.dkr.ecr.us-east-1.amazonaws.com/tweetapp-springboot
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')

  install:
    runtime-versions:
      java: corretto11

  build:
    commands:
      - echo creating jar of project
      - mvn clean install
      - echo jar created on `date`
      - echo starting docker process
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo $REPOSITORY_URI
      - echo $IMAGE_TAG
      - echo $REPOSITORY_URI:latest
      - echo $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Build completed successfully on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"cicd-container","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinition.json
      - cat imagedefinitions.json

artifacts:
  files:
    - imagedefinition.json
    - target/sample-codebuild.jar
